### ISSUE TITLE
Adams method incorrect

### ISSUE THREAD

**Issue by martinlackner** [crflynn/voting#5]
The Adams method should give each party one seat before assigning a second seat to a party.

For example,
votes = [10,1]
seats = 2
adams(votes, seats)

should return [1, 1], but returns [2.0, 0.0].

**Comment by crflynn** [comment]
Hey I'm not sure about this one.

https://www.coconino.edu/resources/files/pdfs/academics/arts-and-sciences/MAT142/Chapter_9_Apportionment.pdf
https://www.maa.org/press/periodicals/convergence/apportioning-representatives-in-the-united-states-congress-adams-method-of-apportionment

These two sources don't mention anything about assigning seats evenly before increasing. The examples don't seem to support this outcome either.

**Comment by martinlackner** [comment]
This is a consequence of how Adams is defined: Adams corresponds to rounding up. Therefore, no matter what the divisor is, the rounded value is at least 1 (as long as the vote count is >= 1). 

Also, the spreadsheet linked in 
https://www.maa.org/press/periodicals/convergence/apportioning-representatives-in-the-united-states-congress-adams-method-of-apportionment
yields [1, 1] for my example above.

**Comment by crflynn** [comment]
Gotcha, I'll take another look.
